/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsyncButton: typeof import('./src/components/atomic/AsyncButton.vue')['default']
    CheckBoxGroup: typeof import('./src/components/CheckBoxGroup.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DeleteModal: typeof import('./src/components/modal/DeleteModal.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchInput: typeof import('./src/components/atomic/SearchInput.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    StepProgress: typeof import('./src/components/StepProgress.vue')['default']
    SwitchButton: typeof import('./src/components/atomic/SwitchButton.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TogglePassword: typeof import('./src/components/atomic/TogglePassword.vue')['default']
    VerifyInput: typeof import('./src/components/VerifyInput.vue')['default']
  }
}
